name: pypsa-isolated
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.11
  - pypsa
  - atlite
  - numpy
  - pandas
  - xarray
  - matplotlib
  - folium
  - jupyter
  - openpyxl
  - pip
  - pip:
      - highspy
